In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import statsmodels.api as sm
import glob
import os
import openpyxl
import pdfkit

### Leer todos los archivos Base

In [43]:
todos=[]
for f in glob.glob(os.path.join("C:/users/fadg1/onedrive/escritorio/analytics/green_movil/data/serviciosne/*.xlsx")):
    df=pd.read_excel(f)
    todos.append(pd.read_excel(f))

C:\Users\fadg1\anaconda3\lib\site-packages\openpyxl\worksheet\_reader.py:312: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

### Concatenar archivos Base

In [5]:
df = pd.concat(todos,ignore_index="True")

### Eliminar nulos archivos Base

In [6]:
df = df.fillna(0)

### Leer Excel y convertir a csv archivos Base

In [7]:
df.to_excel("C:/users/fadg1/onedrive/escritorio/analytics/green_movil/data/serviciosne/Todossne.xlsx", index = None, header=True)
todosne = pd.read_excel(r"C:/users/fadg1/onedrive/escritorio/analytics/green_movil/data/serviciosne/Todossne.xlsx")
todosne.to_csv(r"C:/users/fadg1/onedrive/escritorio/analytics/green_movil/data/serviciosne/Todossne.csv", index = None,  header=True)

### Leer todos los archivos revision

In [10]:
 todos1=[]
for f in glob.glob(os.path.join("C:/users/fadg1/onedrive/escritorio/analytics/green_movil/data/archivos de consulta/02 actividad bus sc/*.csv")):
    df1=pd.read_csv(f)
    todos1.append(pd.read_csv(f))

### Concatenar archivos revision

In [11]:
df1 = pd.concat(todos1,ignore_index="True")

### Eliminar nulos archivos revision

In [12]:
df1 = df1.fillna(0)

In [27]:
df1.head()

,Fecha,Operador,CodigoBus,NumeroBus,NumEventosBus,ServicioBus,Linea,Coche,ViajeLinea,OrdenViaje,...,HoraTeorica,HoraReferencia,HoraLlegada,HoraSalida,Evento,TiempoRegulacion,Alarma,TiempoAperturaPuertas,Conductor,NombreConductor
0,10/1/2021,[111] D,Z15-0025,150025,531 eventos,CDGLG0003,[1295] T07,3,0,1,...,4:12:00,4:12:00,0,0,Inicio Viaje - Cocheras - Cocheras,0:00,0,0.0,157951.0,DIEGO FERNEY MARIN CUBILLOS
1,10/1/2021,[111] D,Z15-0025,150025,531 eventos,CDGLG0003,[1295] T07,3,0,1,...,4:24:00,4:24:00,0,0,Fin Viaje,0:00,0,0.0,157951.0,DIEGO FERNEY MARIN CUBILLOS
2,10/1/2021,[111] D,Z15-0025,150025,531 eventos,CDGLG0003,[1295] T07,3,1,2,...,4:24:00,4:24:00,0,0,Inicio Viaje - Linea - Regulacion,0:00,0,0.0,157951.0,DIEGO FERNEY MARIN CUBILLOS
3,10/1/2021,[111] D,Z15-0025,150025,531 eventos,CDGLG0003,[1295] T07,3,1,2,...,4:26:45,4:26:45,4:25:32,4:25:46,0,0:00,0,0.0,157951.0,DIEGO FERNEY MARIN CUBILLOS
4,10/1/2021,[111] D,Z15-0025,150025,531 eventos,CDGLG0003,[1295] T07,3,1,2,...,4:28:03,4:28:03,4:26:48,4:26:48,0,0:00,0,0.0,157951.0,DIEGO FERNEY MARIN CUBILLOS

### camabiar nombre de columna

In [30]:
df1.rename(columns={'CodigoBus': 'Bus'}, inplace=True)

In [31]:
df1.head()

,Fecha,Operador,Bus,NumeroBus,NumEventosBus,ServicioBus,Linea,Coche,ViajeLinea,OrdenViaje,...,HoraTeorica,HoraReferencia,HoraLlegada,HoraSalida,Evento,TiempoRegulacion,Alarma,TiempoAperturaPuertas,Conductor,NombreConductor
0,10/1/2021,[111] D,Z15-0025,150025,531 eventos,CDGLG0003,[1295] T07,3,0,1,...,4:12:00,4:12:00,0,0,Inicio Viaje - Cocheras - Cocheras,0:00,0,0.0,157951.0,DIEGO FERNEY MARIN CUBILLOS
1,10/1/2021,[111] D,Z15-0025,150025,531 eventos,CDGLG0003,[1295] T07,3,0,1,...,4:24:00,4:24:00,0,0,Fin Viaje,0:00,0,0.0,157951.0,DIEGO FERNEY MARIN CUBILLOS
2,10/1/2021,[111] D,Z15-0025,150025,531 eventos,CDGLG0003,[1295] T07,3,1,2,...,4:24:00,4:24:00,0,0,Inicio Viaje - Linea - Regulacion,0:00,0,0.0,157951.0,DIEGO FERNEY MARIN CUBILLOS
3,10/1/2021,[111] D,Z15-0025,150025,531 eventos,CDGLG0003,[1295] T07,3,1,2,...,4:26:45,4:26:45,4:25:32,4:25:46,0,0:00,0,0.0,157951.0,DIEGO FERNEY MARIN CUBILLOS
4,10/1/2021,[111] D,Z15-0025,150025,531 eventos,CDGLG0003,[1295] T07,3,1,2,...,4:28:03,4:28:03,4:26:48,4:26:48,0,0:00,0,0.0,157951.0,DIEGO FERNEY MARIN CUBILLOS

### Convertir xlsx a csv archivos revision

In [14]:
df1.to_csv("C:/users/fadg1/onedrive/escritorio/analytics/green_movil/data/archivos de consulta/02 actividad bus sc/actividadbustodos.csv", index = None, header=True)

### Filtrar archivos revision

In [16]:
filtrado = df[(df.Responsable == "Cop") & (df.Observación == "F2 inicio_fin Ruta") | (df.Observación == "Estados de Localización")]

### camabiar nombre de columna

In [33]:
filtrado.rename(columns={'Viaje Línea': 'ViajeLinea'}, inplace=True)

C:\Users\fadg1\anaconda3\lib\site-packages\pandas\core\frame.py:4441: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

In [42]:
filtrado.head()

,Fecha,Id_Ick,Zona,Ruta_CE,COP,ServicioBus,Coche,ViajeLinea,Sentido,Bus,...,Observación,Validador EIC,Titulo Validador,Revisor,Objeta,Pruebas,Observacion_novedad,Responsable_#2,Servicio Bus,Elisabeth Garcia
948,01/10/2021,18100890.0,SAN CRISTÓBAL,139,GAVIOTAS A,CDGK30028,28.0,3.0,Ida,Z15-4194,...,Estados de Localización,1.0,Km por mejor escenario con estados de localiza...,0.0,0.0,0.0,0.0,0.0,0,0
949,01/10/2021,18133388.0,SAN CRISTÓBAL,T30B,GAVIOTAS A,CDGIT0012,12.0,1.0,Ida,Z15-4228,...,Estados de Localización,1.0,Km por mejor escenario con estados de localiza...,0.0,0.0,0.0,0.0,0.0,0,0
950,01/10/2021,18134328.0,SAN CRISTÓBAL,T13,GAVIOTAS A,CDGR50030,30.0,3.0,Ida,Z15-7051,...,Estados de Localización,1.0,Km por mejor escenario con estados de localiza...,0.0,0.0,0.0,0.0,0.0,0,0
957,01/10/2021,18097845.0,USAQUÉN,BA900,TOBERÍN,CNJLKG003,16.0,2.0,Ida,Z10-4702,...,Estados de Localización,1.0,Km por mejor escenario con estados de localiza...,0.0,0.0,0.0,0.0,0.0,0,0
958,01/10/2021,18139131.0,USAQUÉN,BA900,TOBERÍN,CNJLK0009,9.0,4.0,Ida,Z10-4499,...,Estados de Localización,1.0,Km por mejor escenario con estados de localiza...,0.0,0.0,0.0,0.0,0.0,0,0

### Exportar archivo a CSV

In [17]:
filtrado.to_csv(r"C:/users/fadg1/onedrive/escritorio/analytics/green_movil/data/serviciosne/filtradoTodossne.csv", index = None,  header=True)

### Unir archivos base y revision

In [38]:
output1 = pd.merge(df1, filtrado, on = ['Bus','ViajeLinea','ServicioBus','Coche'], how ='inner')

### Selecionar informacion para informe

In [39]:
derived_df = output1.filter(['Fecha_y', 'Operador', 'NumeroBus',
       'NumEventosBus', 'Linea', 'OrdenViaje', 'IDViaje', 'Tipo', 'Nodo',
       'Descripcion', 'HoraTeorica', 'HoraReferencia', 'HoraLlegada',
       'HoraSalida', 'Evento', 'TiempoRegulacion', 'Alarma',
       'TiempoAperturaPuertas', 'Conductor', 'NombreConductor'])

In [40]:
derived_df.head()

,Fecha_y,Operador,NumeroBus,NumEventosBus,Linea,OrdenViaje,IDViaje,Tipo,Nodo,Descripcion,HoraTeorica,HoraReferencia,HoraLlegada,HoraSalida,Evento,TiempoRegulacion,Alarma,TiempoAperturaPuertas,Conductor,NombreConductor
0,01/10/2021,[111] D,150025,531 eventos,[1295] T07,2,2,Parada,56011,586E13_Estaci¢n 1 de Mayo,4:24:00,4:24:00,0,0,Inicio Viaje - Linea - Regulacion,0:00,0,0.0,157951.0,DIEGO FERNEY MARIN CUBILLOS
1,01/10/2021,[111] D,150025,531 eventos,[1295] T07,2,2,Parada,55514,212A13_Batall¢n Jos‚ Mar¡a Rosillo,4:26:45,4:26:45,4:25:32,4:25:46,0,0:00,0,0.0,157951.0,DIEGO FERNEY MARIN CUBILLOS
2,01/10/2021,[111] D,150025,531 eventos,[1295] T07,2,2,Parada,55375,102A13_Carrera 6,4:28:03,4:28:03,4:26:48,4:26:48,0,0:00,0,0.0,157951.0,DIEGO FERNEY MARIN CUBILLOS
3,01/10/2021,[111] D,150025,531 eventos,[1295] T07,2,2,Parada,55378,104A13_Br. Granada Sur,4:28:54,4:28:54,4:27:15,4:27:15,0,0:00,0,0.0,157951.0,DIEGO FERNEY MARIN CUBILLOS
4,01/10/2021,[111] D,150025,531 eventos,[1295] T07,2,2,Parada,55185,002A13_Carrera 2,4:30:04,4:30:04,4:27:40,4:27:40,0,0:00,0,0.0,157951.0,DIEGO FERNEY MARIN CUBILLOS

### Convertir a CSV y xlsx para informe

In [41]:
derived_df.to_csv(r"C:/users/fadg1/onedrive/escritorio/analytics/green_movil/data/soporte.csv", index = None,  header=True)
derived_df.to_excel("C:/users/fadg1/onedrive/escritorio/analytics/green_movil/data/soporte.xlsx", index = None, header=True)